export const PLANT = '#6CC002'
export const BUG = '#FF5341'
export const AQUA = '#01B8CE'
export const BEAST = '#FFB812'
export const REPTILE = '#DC8BE4'
export const BIRD = '#FF8BBD'
export const MECH = '#C6BDD3'
export const DAWN = '#BECEFF'
export const DUSK = '#129092'
export const EGG = '#8D65FF'

export const HP = '#3AC279'
export const SKILL = '#6A39C2'
export const MORALE = '#C23A3B'
export const SPEED = '#F7AC09'
